parser grammar DecaParser;

options {
    // Default language but name it anyway
    //
    language  = Java;

    // Use a superclass to implement all helper
    // methods, instance variables and overrides
    // of ANTLR default methods, such as error
    // handling.
    //
    superClass = AbstractDecaParser;

    // Use the vocabulary generated by the accompanying
    // lexer. Maven knows how to work out the relationship
    // between the lexer and parser and will build the
    // lexer before the parser. It will also rebuild the
    // parser if the lexer changes.
    //
    tokenVocab = DecaLexer;

}

// which packages should be imported?
@header {
    import fr.ensimag.deca.tree.*;
    import java.io.PrintStream;
}

@members {
    @Override
    protected AbstractProgram parseProgram() {
        return prog().tree;
    }
}

prog returns[AbstractProgram tree]
    : list_classes main EOF {
            assert($list_classes.tree != null);
            assert($main.tree != null);
            $tree = new Program($list_classes.tree, $main.tree);
            setLocation($tree, $list_classes.start, $EOF);
        }
    ;

main returns[AbstractMain tree]
    : /* epsilon */ {
            $tree = new EmptyMain();
        }
    | block {
            assert($block.decls != null);
            assert($block.insts != null);
            $tree = new Main($block.decls, $block.insts);
            setLocation($tree, $block.start);
        }
    ;

block returns[ListDeclVar decls, ListInst insts]
    : OBRACE list_decl list_inst CBRACE {
            assert($list_decl.tree != null);
            assert($list_inst.tree != null);
            $decls = $list_decl.tree;
            $insts = $list_inst.tree;
        }
    ;

list_decl returns[ListDeclVar tree]
@init   {
            $tree = new ListDeclVar();
        }
    : decl_var_set[$tree]*
    ;

decl_var_set[ListDeclVar l]
    : type list_decl_var[$l,$type.tree] SEMI
    ;

list_decl_var[ListDeclVar l, AbstractType t]
    : dv1=decl_var[$t] {
        $l.add($dv1.tree);
        } (COMMA dv2=decl_var[$t] {
            $l.add($dv2.tree);
        }
      )*
    ;

decl_var[AbstractType t] returns[AbstractDeclVar tree]
@init   {
    AbstractInitialization init = new NoInitialization();
        }
    : i=ident {
            assert($i.tree != null);
        }
      (EQUALS e=expr {
            assert($e.tree != null);
            init = new Initialization($e.tree);
            setLocation(init, $e.start, $e.stop);
        }
      )? {
            $tree = new DeclVar(t, $i.tree, init);
            if ($e.stop != null) {
                setLocation($tree, $i.start, $e.stop);
            } else {
                setLocation($tree, $i.start);
            }
        }
    ;

list_inst returns[ListInst tree]
@init {
        $tree = new ListInst();
}
    : (inst {
            $tree.add($inst.tree);
        }
      )*
    ;

inst returns[AbstractInst tree]
    : e1=expr SEMI {
            assert($e1.tree != null);
            $tree = $e1.tree;
        }
    | SEMI {
            $tree = new NoOperation();
            setLocation($tree, $SEMI);
        }
    | PRINT OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree = new Print(false, $list_expr.tree);
            setLocation($tree, $PRINT, $SEMI);
        }
    | PRINTLN OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree = new Println(false, $list_expr.tree);
            setLocation($tree, $PRINTLN, $SEMI);
        }
    | PRINTX OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree = new Print(true, $list_expr.tree);
            setLocation($tree, $PRINTX, $SEMI);
        }
    | PRINTLNX OPARENT list_expr CPARENT SEMI {
            assert($list_expr.tree != null);
            $tree = new Println(true, $list_expr.tree);
            setLocation($tree, $PRINTLNX, $SEMI);
        }
    | if_then_else {
            assert($if_then_else.tree != null);
            $tree = $if_then_else.tree;
        }
    | assertion {
            assert($assertion.tree != null);
            $tree = $assertion.tree;
        }
    | WHILE OPARENT condition=expr CPARENT OBRACE body=list_inst CBRACE {
            assert($condition.tree != null);
            assert($body.tree != null);
            $tree = new While($condition.tree , $body.tree );
            setLocation($tree, $WHILE, $CBRACE);
        }
    | RETURN expr SEMI {
            assert($expr.tree != null);
            $tree = new Return($expr.tree);
            setLocation($tree, $RETURN, $SEMI);
        }
    ;

if_then_else returns[IfThenElse tree]
@init {
    IfThenElse current;
}
    : if1=IF OPARENT condition=expr CPARENT OBRACE li_if=list_inst CBRACE {
            assert($condition.tree != null);
            assert($li_if.tree != null);
            $tree = new IfThenElse($condition.tree, $li_if.tree, new ListInst());
            setLocation($tree, $if1, $CBRACE);
            current = $tree;
        }
      (ELSE elsif=IF OPARENT elsif_cond=expr CPARENT OBRACE elsif_li=list_inst CBRACE {
            assert($elsif_cond.tree != null);
            assert($elsif_li.tree != null);
            IfThenElse nested = new IfThenElse($elsif_cond.tree, $elsif_li.tree, new ListInst());
            setLocation(nested, $ELSE, $CBRACE);
            current.addElseBranch(nested);
            current = nested;
        }
      )*
      (ELSE OBRACE li_else=list_inst CBRACE {
            assert($li_else.tree != null);
            current.setElseBranch($li_else.tree);
        }
      )?
    ;
assertion returns[Assertion tree]
@init {
    Assertion current;
}
    : assertion1=ASSERT OPARENT condition=expr CPARENT SEMI {
            assert($condition.tree != null);
            $tree = new Assertion($condition.tree);
            setLocation($tree, $assertion1);
            current = $tree;
        }
      | assertion1=ASSERT OPARENT condition=expr COMMA e=list_expr CPARENT SEMI {
          assert($condition.tree != null);
          $tree = new Assertion($condition.tree, $e.tree);
          setLocation($tree, $assertion1);
          current = $tree;
      }

    ;
list_expr returns[ListExpr tree]
@init   {
            $tree = new ListExpr();
        }
    : (e1=expr {
                $tree.add($e1.tree);
        }
       (COMMA e2=expr {
                 $tree.add($e2.tree);
        }
       )* )?
    ;

expr returns[AbstractExpr tree]
    : assign_expr {
            assert($assign_expr.tree != null);
            $tree = $assign_expr.tree;
        }

    ;

assign_expr returns[AbstractExpr tree]
    : e=or_expr (
        /* condition: expression e must be a "LVALUE" */ {
            if (! ($e.tree instanceof AbstractLValue)) {
                throw new InvalidLValue(this, $ctx);
            }
            $tree = $e.tree;
        }
        EQUALS e2=assign_expr {
            assert($e.tree != null);
            assert($e2.tree != null);
            $tree = new Assign((AbstractLValue) $e.tree, $e2.tree);
            setLocation($tree, $e.start, $e2.stop);
        }
      | /* epsilon */ {
            assert($e.tree != null);
            $tree = $e.tree;
        }
      )
    ;

or_expr returns[AbstractExpr tree]
    : e=and_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=or_expr OR e2=and_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Or($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
       }
    ;

and_expr returns[AbstractExpr tree]
    : e=eq_neq_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    |  e1=and_expr AND e2=eq_neq_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new And($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    ;

eq_neq_expr returns[AbstractExpr tree]
    : e=inequality_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=eq_neq_expr EQEQ e2=inequality_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Equals($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=eq_neq_expr NEQ e2=inequality_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new NotEquals($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    ;

inequality_expr returns[AbstractExpr tree]
    : e=sum_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=inequality_expr LEQ e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new LowerOrEqual($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=inequality_expr GEQ e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new GreaterOrEqual($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=inequality_expr GT e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Greater($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=inequality_expr LT e2=sum_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Lower($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=inequality_expr INSTANCEOF type {
            assert($e1.tree != null);
            assert($type.tree != null);
            if(!($type.tree instanceof Identifier)) {
                throw new InstanceOfArrayNotAllowed(this, $ctx);
            }
            $tree = new Instanceof($e1.tree, (Identifier)$type.tree);
            setLocation($tree, $e1.start, $type.stop);
        }
    ;


sum_expr returns[AbstractExpr tree]
    : e=mult_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=sum_expr PLUS e2=mult_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Plus($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=sum_expr MINUS e2=mult_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Minus($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    ;

mult_expr returns[AbstractExpr tree]
    : e=unary_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=mult_expr TIMES e2=unary_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Multiply($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=mult_expr SLASH e2=unary_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Divide($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    | e1=mult_expr PERCENT e2=unary_expr {
            assert($e1.tree != null);
            assert($e2.tree != null);
            $tree = new Modulo($e1.tree, $e2.tree);
            setLocation($tree, $e1.start, $e2.stop);
        }
    ;

unary_expr returns[AbstractExpr tree]
    : op=MINUS e=unary_expr {
            assert($e.tree != null);
            $tree = new UnaryMinus($e.tree);
            setLocation($tree, $op, $e.stop);
        }
    | op=EXCLAM e=unary_expr {
            assert($e.tree != null);
            $tree = new Not($e.tree);
            setLocation($tree, $op, $e.stop);
        }
    | select_expr {
            assert($select_expr.tree != null);
            $tree = $select_expr.tree;
        }
    ;

select_expr returns[AbstractExpr tree]
    : e=primary_expr {
            assert($e.tree != null);
            $tree = $e.tree;
        }
    | e1=select_expr DOT i=ident {
            assert($e1.tree != null);
            assert($i.tree != null);
            $tree = new Selection($e1.tree, $i.tree);
            setLocation($tree, $e1.start, $i.stop);

        }
        (o=OPARENT args=list_expr CPARENT {
            // we matched "e1.i(args)"
            assert($args.tree != null);
            $tree = new MethodCall($e1.tree, $i.tree, $args.tree);
            setLocation($tree, $e1.start, $CPARENT);
        }
        | /* epsilon */ {
            // we matched "e.i"
        }
        )
    ;

primary_expr returns[AbstractExpr tree]
    : ident {
            assert($ident.tree != null);
            $tree = $ident.tree;
        }
    | m=ident OPARENT args=list_expr CPARENT {
            assert($args.tree != null);
            assert($m.tree != null);
            AbstractExpr thiz = new This(true);
            setLocation(thiz, $m.start, $m.stop);

            $tree = new MethodCall(thiz, $m.tree, $args.tree);
            setLocation($tree, $m.start, $CPARENT);
        }
    | OPARENT expr CPARENT {
            assert($expr.tree != null);
            $tree = $expr.tree;
        }
    | array=primary_expr OBRACKET expr CBRACKET {
        assert($array.tree != null);
        assert($expr.tree != null);
        $tree = new Index($array.tree, $expr.tree);
        setLocation($tree, $array.start);
       }
    | READINT OPARENT CPARENT {
        $tree = new ReadInt();
        setLocation($tree, $READINT, $CPARENT);
        }
    | READFLOAT OPARENT CPARENT {
        $tree = new ReadFloat();
        setLocation($tree, $READFLOAT, $CPARENT);
        }
    | NEW type OBRACKET expr CBRACKET {
        assert($expr.tree != null);
        assert($type.tree != null);
        $tree = new NewArray($type.tree, $expr.tree);
        setLocation($tree, $NEW);
    }
    | NEW ident OPARENT CPARENT {
            assert($ident.tree != null);
            $tree = new New($ident.tree);
            setLocation($tree, $NEW, $CPARENT);
        }
    | cast=OPARENT type CPARENT OPARENT expr CPARENT {
            assert($type.tree != null);
            assert($expr.tree != null);
            if(!($type.tree instanceof Identifier)) {
                throw new InstanceOfArrayNotAllowed(this, $ctx);
            }
            $tree = new Cast((Identifier)$type.tree, $expr.tree);
            setLocation($tree, $cast, $CPARENT);
        }
    | literal {
            assert($literal.tree != null);
            $tree = $literal.tree;
        }
    ;

type returns[AbstractType tree]
    :  ident {
            assert($ident.tree != null);
            $tree = (AbstractType)$ident.tree;
            setLocation($tree, $ident.start);
        }
        (OBRACKET CBRACKET
        {
                    $tree = new Array($tree);
                    setLocation($tree, $ident.start);
        })*
    ;

literal returns[AbstractExpr tree]
    : INT {
            int value;
            try {
                value = Integer.parseInt($INT.text);
            } catch (NumberFormatException e) {
                throw new OutOfRangeLiteral(this, $ctx);
            }
            $tree = new IntLiteral(value);
            setLocation($tree, $INT);
        }
    | fd=FLOAT {
            float value;
            try {
                value = FloatParser.checkedParseFloat($fd.text);
                $tree = new FloatLiteral(value);
            } catch (IllegalArgumentException e) {
                throw new OutOfRangeLiteral(this, $ctx);
            }
            setLocation($tree, $fd);
        }
    | STRING {
        StringBuilder builder = new StringBuilder();
        String text = $STRING.text;
        boolean escape  = false;
        for (int i = 1; i < text.length()-1; i++) {
            if (escape){
                builder.append(text.charAt(i));
                escape = false;
                continue;
            }
            if (text.charAt(i) == '\\') {
                escape = true;
                continue;
            }
            builder.append(text.charAt(i));
        }
        $tree = new StringLiteral(builder.toString());
        setLocation($tree, $STRING);
        }
    | TRUE {
        $tree = new BooleanLiteral(true);
        setLocation($tree, $TRUE);
        }
    | FALSE {
        $tree = new BooleanLiteral(false);
        setLocation($tree, $FALSE);
        }
    | THIS {
        $tree = new This(false);
        setLocation($tree, $THIS);
        }
    | NULL {
        $tree = new Null();
        setLocation($tree, $NULL);
        }
    ;

ident returns[AbstractIdentifier tree]
    : IDENT {
            $tree = new Identifier(getDecacCompiler().createSymbol($IDENT.text));
            setLocation($tree, $IDENT);
        }
    ;

/****     Class related rules     ****/

list_classes returns[ListDeclClass tree]
@init{
    $tree = new ListDeclClass();
}
    :
      (c1=class_decl {
            $tree.add($c1.tree);
        }
      )*
    ;

class_decl returns[AbstractDeclClass tree]
    : CLASS name=ident superclass=class_extension OBRACE body=class_body CBRACE {
            $tree = new DeclClass($name.tree, $superclass.tree, $body.fields, $body.methods);
            setLocation($tree, $CLASS, $CBRACE);
        }
    ;

class_extension returns[AbstractIdentifier tree]
    : EXTENDS ident {
        $tree = $ident.tree;
        }
    | /* epsilon */ {
        }
    ;

class_body returns[ListDeclField fields, ListDeclMethod methods]
    @init{
        $fields = new ListDeclField();
        $methods = new ListDeclMethod();
    }
    : (m=decl_method {
            $methods.add($m.tree);
        }
      | decl_field_set[$fields]
      )*
    ;

decl_field_set[ListDeclField l]
    : v=visibility t=type list_decl_field[$l, $v.tree, $t.tree]
      SEMI
    ;

visibility returns[Visibility tree]
    : /* epsilon */ {
        $tree = Visibility.PUBLIC;
        }
    | PROTECTED {
        $tree = Visibility.PROTECTED;
        }
    ;

list_decl_field[ListDeclField l, Visibility v, AbstractType t]

    : dv1=decl_field[$v, $t] {
        $l.add($dv1.tree);
        }
        (COMMA dv2=decl_field[$v, $t] {
            $l.add($dv2.tree);
        }
      )*
    ;

decl_field[Visibility v, AbstractType t] returns[DeclField tree]
@init   {
    AbstractInitialization init = new NoInitialization();
}
    : i=ident {
        assert($i.tree != null);
        }
      (EQUALS e=expr {
            assert($e.tree != null);
            init = new Initialization($e.tree);
            setLocation(init, $e.start, $e.stop);
        }
      )? {
            $tree = new DeclField(v, t, $i.tree, init);
            if ($e.stop != null) {
                setLocation($tree, $i.start, $e.stop);
            } else {
                setLocation($tree, $i.start);
            }
        }
    ;

decl_method returns[DeclMethod tree]
@init {
}
    : type ident OPARENT params=list_params CPARENT (block {
            assert($type.tree != null);
            assert($ident.tree != null);
            assert($params.tree != null);
            assert($block.decls != null);
            assert($block.insts != null);

            MethodBody body = new MethodBody($block.decls, $block.insts);
            setLocation(body, $block.start, $block.stop);

            $tree = new DeclMethod($type.tree, $ident.tree, $params.tree, body);
            setLocation($tree, $type.start, $block.stop);
        }
      | ASM OPARENT code=multi_line_string CPARENT SEMI {
            assert($code.text != null);
            StringLiteral s = new StringLiteral($code.text.substring(1, $code.text.length() - 1)
               .replaceAll("\\\\\\\\", "\\\\")
               .replaceAll("\\\\\"", "\"")
            );
            s.setLocation($code.location);

            MethodBodyAsm methodBodyAsm = new MethodBodyAsm(s);
            setLocation(methodBodyAsm, $code.start, $code.stop);

            $tree = new DeclMethod($type.tree, $ident.tree, $params.tree, methodBodyAsm);
            setLocation($tree, $code.start, $code.stop);
        }
      ) {
        }
    ;

list_params returns[ListDeclParam tree]
@init{
    $tree = new ListDeclParam();
}
    : (p1=param {
            $tree.add($p1.tree);
        } (COMMA p2=param {
            $tree.add($p2.tree);
        }
      )*)?
    ;
    
multi_line_string returns[String text, Location location]
    : s=STRING {
            $text = $s.text;
            $location = tokenLocation($s);
        }
    | s=MULTI_LINE_STRING {
            $text = $s.text;
            $location = tokenLocation($s);
        }
    ;

param returns[DeclParam tree]
    : type ident {
        assert($type.tree != null);
        assert($ident.tree != null);
        $tree = new DeclParam($type.tree, $ident.tree);
        setLocation($tree, $type.start, $ident.stop);
    }
    ;
